#!/bin/bash
set -e

HERE="$(dirname "$(readlink -f "$0")")"

export FTHR_ENGINE="$HERE/usr/bin/FTHRclips"
export PYTHONHOME="$HERE/usr"
export PYTHONPATH="$HERE/usr/lib/python3/dist-packages:$PYTHONPATH"
export LD_LIBRARY_PATH="$HERE/usr/lib:$HERE/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
export QT_PLUGIN_PATH="$HERE/usr/plugins"
export QT_QPA_PLATFORM_PLUGIN_PATH="$HERE/usr/plugins/platforms"

exec "$HERE/usr/bin/python3" "$HERE/usr/share/fthr-clips/FTHR_UI/main.py" "$@"
